### ISSUE TITLE
What is the initial, default memory footprint after setup (for each new instance)?

### ISSUE THREAD

**Issue by LeeteqXV** [hexparrot/qubes-crux#2]
Ref. the README.txt specifying to assign 2Gb memory initially for the kernel operations to successfully complete.
What is the minimum RAM requirement for a new VM instance based on Qubes-CRUX?
For example if we only want a Disposable VM that may run 1-15 browser tabs of normal web pages, plus the buil-in File Manager and for example 1 instance of the gEdit / Pluma / Kate editor, what should the initial size be set to?

**Comment by hexparrot** [comment]
2gb might be overkill for building the kernel, but it did fail at 512 on my system. 

Beyond that, my appvms have always been left at the default memory, so somewhere in the lower hundreds works just fine. This will be set independently from the template VMs being left set at 2gb, too. 

CRUX operates with a minimalist philosophy so it’s highly likely that whatever fits the bill for your normal Fedora/Debian appvms will be much more than even what CRUX needs. 

the kernel config provided works has the least amount of features I think is even possible to make a workable system, so the kernel footprint should be even more accommodating for low memory appvms. 

All that said, just as with any appvm, you can check the mem usage (top in domU and xentop in dom0) to adjust accordingly. 

The one thing that needs to be fixed is that currently the swap file isn’t in use, so aiming for minimal memory to operate might be a counterproductive tweak at this point. I’m working on this actively and will be able to provide instructions on existing templateVMs, too.
