### ISSUE TITLE
20_install_packages script

### ISSUE THREAD

**Issue by c4tzz** [hexparrot/qubes-crux#6]
Hi, any ideas how to fix?
![pkgadd error](https://user-images.githubusercontent.com/49844258/64200659-a7ab9680-ce95-11e9-8ef2-49dc767c68fa.png)

**Comment by hexparrot** [comment]
Not sure what's going on there, but have you first tried `00_full_install`?

The thing that strikes me as odd here is that some packages are already installed--was this from a previously aborted attempt?  Is this the second time running it in succession?

**Comment by c4tzz** [comment]
Hi, Hexparrot.
00_full_install works good, installation complete but it force same error on step 02 and i can't get kernel from hvm template.
> qvm-run -p crux 'cat /usr/ports/qubes-crux/helpers/kernel.tar.gz' | tar xzf -
gives me "connection" error on dom0.
02 script can't install opt and xorg packages. i dont know why. 

qvm-create --class StandaloneVM --label red --property virt_mode=hvm crux
qvm-prefs crux memory 2048
qvm-prefs crux maxmem 4096
qvm-start crux --cdrom=untrusted:/home/user/Downloads/crux-3.5.iso
then use your instructions. maybe i need grow private/root storage by qvm-volume extend?

**Comment by hexparrot** [comment]
Is your ISO intact?

Compare the sr0 size, yours is about half the size.

$ md5sum crux-3.5.iso 
eb0c9b75322ba240f229ec9834feddfd  crux-3.5.iso

![qubes](https://user-images.githubusercontent.com/4994619/64203433-3f829380-ce48-11e9-9060-6f6ad7cee87c.png)

**Comment by c4tzz** [comment]
Oh my god. Thank you. You're basically right.
[user@untrusted Downloads]$ ls -lh crux-3.5.iso 
-rw-rw-r-- 1 user user 375M Aug 30 19:14 crux-3.5.iso
